<a href="https://colab.research.google.com/github/hank199599/deep_learning_keras_log/blob/main/Chapter2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2-1 初探神經網路：第一支神經網路


## MINIST 資料集圖片辨識
深度學習的「Hello World!」
1. 載入mnist資料集，含(train_images,train_labels)和(test_images,test_labels)
2. 用兩個Dense層架構(network.add())了一個神經網路
3. 用network.compile()來編譯神經網路，此時要指定optimmizer、loss、metrices三個參數
4.要將輸入資料集做前處理，用reshape()和astype()來做 
5. 對輸入的標籤做分類標碼
6. 用network.fit()來進行訓練
7. 用network.evaluate()評估成果

In [14]:
# 在Keras中載入MNIST資料集
from keras.datasets import mnist

(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

查看驗證資料

In [15]:
train_images.shape

(60000, 28, 28)

In [16]:
len(train_labels)

60000

In [17]:
train_labels
#標籤是0-9之間的數字，資料型別是unit8

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

查看測試資料

In [18]:
test_images.shape

(10000, 28, 28)

In [19]:
len(test_labels)

10000

In [20]:
test_labels
#標籤是0-9之間的數字，資料型別是unit8

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

# 整體操作流程
①  我們提供訓練集 train_images 和 train_labels 給神經網路  
②  神經網路學習把圖片加以歸類,並且和每張圖片的標籤對比,如果歸類錯誤就加以修正。  
③最後,我們要求神經網路對 test_images 中的圖片進行預測、並進行驗證,確 認是否與 test_labels 中記錄的標籤符合。
 

神經網路架構

## **密集層**/全連接層(fully connected)  
![pic-1](https://ithelp.ithome.com.tw/upload/images/20190925/20120549IXrUJjgcpN.png)  
指前後層的神經元彼此連接在一起，  
前一層神經元皆對應到後一層的神經元。

In [21]:
from keras import models
from keras import layers

network = models.Sequential()
network.add(layers.Dense(512,activation="relu",input_shape=(28*28,)))
network.add(layers.Dense(10,activation='softmax'))

In [22]:
network.compile(
    optimizer = 'rmsprop', # 指定優化器
    loss = 'categorical_crossentropy', # 指定損失函數
    metrics = ['accuracy'] # 指定評量準則
)

## 準備圖片資料
reshape 跟 astype 是 NumPy 陣列的method

In [24]:
train_images = train_images.reshape((60000,28*28))
train_images = train_images.astype('float32')/ 255

test_images = test_images.reshape((10000,28*28))
test_images = test_images.astype('float32')/ 255

對標籤進行分類標碼

In [25]:
from keras.utils import to_categorical

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

## 進行訓練

In [31]:
network.fit(train_images,train_labels,epochs=5,batch_size=128)

Epoch 1/5
469/469 [==============================] - 4s 9ms/step - loss: 0.2442 - accuracy: 0.9291
Epoch 2/5
469/469 [==============================] - 4s 9ms/step - loss: 0.2345 - accuracy: 0.9325
Epoch 3/5
469/469 [==============================] - 5s 10ms/step - loss: 0.2248 - accuracy: 0.9345
Epoch 4/5
469/469 [==============================] - 5s 10ms/step - loss: 0.2156 - accuracy: 0.9381
Epoch 5/5
469/469 [==============================] - 4s 9ms/step - loss: 0.2066 - accuracy: 0.9406


## 進行測試

In [32]:
test_loss , test_acc = network.evaluate(test_images,test_labels)
print('test_acc:',test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 29.5613 - accuracy: 0.9161
test_acc: 0.916100025177002


# 2-2 張量 Tensor

In [41]:
import numpy as np

## 純量 (0D張量)
只包含一個數值的張量

In [42]:
x = np.array(12)
x

array(12)

In [34]:
x.ndim

0

## 向量 (1D張量) vector
由一組數值排列而成的陣列

In [35]:
x = np.array([12,3,6,14,7])
x

array([12,  3,  6, 14,  7])

In [36]:
x.ndim

1

## 矩陣 (2D張量)
一個矩陣

In [37]:
x = np.array([[5,78,2,34,0],
        [6,79,3,35,1],
        [7,80,4,36,2]])

In [38]:
x.ndim

2

## 高階張量 (3D張量與其上)
將多個矩陣包裝在一個新陣列中

In [39]:
x = np.array([[[5,78,2,34,0],
        [6,79,3,35,1],
        [7,80,4,36,2]],
        [[5,78,2,34,0],
        [6,79,3,35,1],
        [7,80,4,36,2]],
        [[5,78,2,34,0],
        [6,79,3,35,1],
        [7,80,4,36,2]]])

In [40]:
x.ndim

3